spring:
  profiles:
    active: local
    
  security:
    oauth2:
      client:
        registration:
          # --- 카카오 설정 ---
          kakao:
            client-id: db0b7acbc796a64b363cc5662e6e2d1e
            client-secret: CfyATwp7dulMr1oCt8mk8BwUjd7NkO8I
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "https://tippable-asha-slaggier.ngrok-free.dev/login/oauth2/code/kakao"
            client-name: Kakao

          # --- 네이버 설정 ---
          naver:
            client-id: NOFlU7zhykC677WPYXKl
            client-secret: R3qLXek3Ov
            client-authentication-method: client_secret_post
            scope:
              - profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "https://tippable-asha-slaggier.ngrok-free.dev/login/oauth2/code/naver"

        # --- Provider 상세 정보 (직접 등록 필요) ---
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오 유저 식별자 필드명

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버는 최상위가 아닌 response 내부에 정보가 있음

jwt:
  secret-key:  "9zLtRoRjkTA/8nxqFk0hpHCancKFOoGMsVBp6rakeQE=" # Replace with a real Base64 encoded secret key
  access-token-validity-in-seconds: 3600 # 1 hour

# 프론트엔드 설정
app:
  frontend:
    url: http://localhost:3000
  oauth2:
    authorized-redirect-uri: http://localhost:3000/auth/callback

server:
  port: 8080
