spring:
  datasource:
    # 실제 운영 환경의 MySQL 데이터베이스 정보를 입력하세요.
    # url: jdbc:mysql://<your-mysql-host>:<port>/<database-name>?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: <your-username>
    # password: <your-password>

  jpa:
    hibernate:
      ddl-auto: validate # 운영 환경에서는 보통 validate, update 또는 none을 사용합니다.
    properties:
      hibernate:
        format_sql: true
